name: Build & Deploy to EC2 from GitHub → GitLab Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitLab Registry
      run: echo "${{ secrets.GITLAB_TOKEN }}" | docker login registry.gitlab.com -u gitlab-ci-token --password-stdin

    - name: Build and Push Backend Image
      run: |
        docker build -t registry.gitlab.com/chamodi2001/incident-tracker-backend:main ./backend
        docker push registry.gitlab.com/chamodi2001/incident-tracker-backend:main

    - name: Build and Push Frontend Image
      run: |
        docker build -t registry.gitlab.com/chamodi2001/incident-tracker-frontend:main ./frontend
        docker push registry.gitlab.com/chamodi2001/incident-tracker-frontend:main

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: SSH to EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/IncidentTracker

          echo Stop running containers
          docker compose down

          echo Log in to GitLab registry
          echo "${{ secrets.GITLAB_TOKEN }}" | docker login registry.gitlab.com -u gitlab-ci-token --password-stdin

          echo Pull updated images
          docker compose pull

          echo Start services
          docker compose up -d

          echo Deployment Complete
EOF
