name: Deploy Backend from GitLab Registry

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH into EC2 and pull Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/incident-tracker

            echo 🛑 Stop old containers
            docker compose down

            echo 📥 Pull latest image from GitLab Container Registry
            echo "${{ secrets.GITLAB_TOKEN }}" | docker login registry.gitlab.com -u gitlab-ci-token --password-stdin

            docker compose pull backend
            docker compose up -d backend

            echo ✅ Deployment Complete
EOF
