name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitLab Registry
      run: echo "${{ secrets.GITLAB_TOKEN }}" | docker login registry.gitlab.com -u gitlab-ci-token --password-stdin

    - name: Build and Push Backend Image
      run: |
        docker build -t registry.gitlab.com/chamodi2001/incident-tracker-backend:main ./backend
        docker push registry.gitlab.com/chamodi2001/incident-tracker-backend:main

    - name: Build and Push Frontend Image
      run: |
        docker build -t registry.gitlab.com/chamodi2001/incident-tracker-frontend:main ./frontend
        docker push registry.gitlab.com/chamodi2001/incident-tracker-frontend:main

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "
          cd ~/incident-tracker &&
          echo '${{ secrets.GITLAB_TOKEN }}' | docker login registry.gitlab.com -u gitlab-ci-token --password-stdin &&
          docker compose pull &&
          docker compose down &&
          docker compose up -d
        "
